### PR TITLE
Update type of `RAWINPUTHEADER.wParam`

### PR DESCRIPTION
**Pull request by johannesegger**
`GetRawInputData` always failed with 0x57 (Invalid param).
Updating the types according to http://pinvoke.net/default.aspx/Structures/RAWINPUTHEADER.html made the call succeed.

### CODE REVIEW

**Comment by Slion** [comment]
@johannesegger Could it be that this was an issue only when running in 64-bits mode? I'm pretty sure this call works in 32-bits.

**Comment by johannesegger** [comment]
Yep, I added another commit that should fix the RAWINPUT structure in 64 bit processes.
`RAWINPUTHEADER` is 16 bytes in 32 bit processes (you hard-coded that as FieldOffset) and 24 bytes in 64 bit processes it seems.

**Comment by johannesegger** [comment]
I added yet another commit that changes `RAWMOUSE` - I think there was something wrong with the offsets so I changed it to sequential layout because that seems less error-prone.

**Comment by Slion** [comment]
Could you get your stuff working? I noticed I have a lot of Pack = 1 in there and those can cause trouble in 64 bits too. For instance RAWINPUTDEVICELIST was not of the right size.

**Comment by johannesegger** [comment]
Yes my stuff worked, thanks. Though I never used `RAWINPUTDEVICELIST`.

**Comment by johannesegger** [comment]
Hm I just noticed that I copied stuff form you and fixed it for me, but I actually never tried your new version. I updated just now and the `Pack = 1` really might do something weird, because RAWINPUT doesn't work correctly. However when I removed just the `Pack = 1` everything worked perfectly. What is `Pack = 1` for? Why did you add it in the first place?

**Comment by johannesegger** [comment]
Take a look at what I found about [C++ alignment](https://en.cppreference.com/w/c/language/object#Alignment). It looks like the default [Pack](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=netframework-4.7.2) behaves exactly like the C++ thing so I guess `Pack` should be removed, shouldn't it?

**Comment by Slion** [comment]
Looks like it. I removed the one that was bothering me.

**Pull request merged**
