### PR TITLE
Remove explicit pack setting

### PR DESCRIPTION
**Pull request by johannesegger**
The alignment with the default [Pack](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=netframework-4.7.2) setting seems to correspond with the default [C++ alignment](https://en.cppreference.com/w/c/language/object#Alignment).

### CODE REVIEW

**Comment by Slion** [comment]
In principle I agree this should be done but it has to be thoroughly tested too and I'm not sure how much time I can invest in that these days. You will find that for most classes it does not matter cause their size will remain the same with and without Pack one.

**Comment by johannesegger** [comment]
Hm ok, I understand. So I'll use a fork of this until this is resolved. Thanks anyway.

**Comment by Slion** [comment]
Ho well, I guess I could test it all when I get there. I case of regressions I can also stick to earlier versions until they get fixed. Version 0.2.0 should be published on NuGet within 30mn.

**Comment by johannesegger** [comment]
Wow great, thanks a lot. It works great, at least for me :-)

**Pull request merged**
